name: Download Data

on:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  # Push image to GitHub Package Registry.
  # See also https://docs.docker.com/docker-hub/builds/
  download:
    runs-on: ubuntu-latest
    # if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Download latest AP Data
        run: ./scripts/download.sh
